### ISSUE TITLE
Publish new package with variable support

### ISSUE THREAD

**Issue by TasneemOlia** [mailersend/mailersend-python#12]
Hi, the read me shows there's variable support but the latest published package on pypi.org is not having support for variables. 

Thanks.

https://pypi.org/project/mailersend/

**Comment by aorfanos** [comment]
Version 0.1.1 has been uploaded to PyPI, including variables support 👍🏼

**Comment by TasneemOlia** [comment]
Thank you. 👍🏼

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
