### ISSUE TITLE
Missing information on docs? camelCase?

### ISSUE THREAD

**Issue by lowercase00** [mailersend/mailersend-python#14]
Hi there, I was wondering if the documentation for the package usage is accurate. I've the class receives the api_key, but it is no mentioned in the docs. Also, I'm curious on what were the reasons to use camelCase in a Python package. Coming from sendgrid, if things workout ok I could also contribute.

Edit: sorry, I missed the `os.environ.get("MAILERSEND_API_KEY")`. Would it make sense to make it so that the api_key is a parameter, instead of necessarily having to use the env_var?

**Comment by aorfanos** [comment]
As of release `v0.1.3` camelCase is deprecated and replaced with snake_case (more info in the docs).

Also, we are planning to give freedom to the developers to choose their own authentication mechanism (env var or parameter) in a further release.
