### ISSUE TITLE
your example not working

### ISSUE THREAD

**Issue by xbln** [mailersend/mailersend-python#21]
neither

`from mailersend import emails

mailer = emails.NewEmail()
mailer.mailersend_api_key = 'eyJ0eXAiOiJKV1QiLCJ....xWbVag'

mail_body = {}

mail_from = {
    "name": "Your Name",
    "email": "no-reply@ihr-corona-test.de",
}

recipients = [
    {
        "name": "Your Client",
        "email": "martin.esche@gmx.de",
    }
]

mailer.set_mail_from(mail_from, mail_body)
mailer.set_mail_to(recipients, mail_body)
mailer.set_subject("Hello!", mail_body)
mailer.set_html_content("This is the HTML content", mail_body)
mailer.set_plaintext_content("This is the text content", mail_body)

print(mailer.send(mail_body))`

nor this

`from mailersend import emails
import os

os.environ['MAILERSEND_API_KEY'] = 'eyJ0eXAiOiJKV1QiLC...WbVag'

mailer = emails.NewEmail()

mail_body = {}

mail_from = {
    "name": "Your Name",
    "email": "no-reply@ihr-corona-test.de",
}

recipients = [
    {
        "name": "Your Client",
        "email": "martin.esche@gmx.de",
    }
]

mailer.set_mail_from(mail_from, mail_body)
mailer.set_mail_to(recipients, mail_body)
mailer.set_subject("Hello!", mail_body)
mailer.set_html_content("This is the HTML content", mail_body)
mailer.set_plaintext_content("This is the text content", mail_body)

print(mailer.send(mail_body))`

is working:
 `401
{"message":"Unauthenticated."}`

The API-Key is OK, it works with Postman.

What´s wrong?

**Comment by mraggi** [comment]
I'm getting exactly the same issue. Has this been resolved?

**Comment by xbln** [comment]
I changed to another mailing provider.



Am Fr., 26. Nov. 2021 um 02:18 Uhr schrieb Miguel Raggi <
***@***.***>:
