### ISSUE TITLE
Reply-to in the README should go without brackets.

### ISSUE THREAD

**Issue by mraggi** [mailersend/mailersend-python#39]
There is a bug in the reply_to part of the README. It says:
```python
reply_to = [
    {
        "name": "Name",
        "email": "reply@domain.com",
    }
]
```
but it should be without the brackets:
```python
reply_to = {
        "name": "Name",
        "email": "reply@domain.com",
    }
```

**Comment by aorfanos** [comment]
Hey @mraggi , thank you for you comment! Have you faced an issue with the this configuration?

I tried the [first send-email example](https://github.com/mailersend/mailersend-python#send-an-email) as is and I received an e-mail as expected.

**Comment by mraggi** [comment]
> Hey @mraggi , thank you for you comment! Have you faced an issue with the this configuration?
> 
> I tried the [first send-email example](https://github.com/mailersend/mailersend-python#send-an-email) as is and I received an e-mail as expected.

But check the reply to address of the email you got. It isn't the one you asked for. If you remove the square brackets (make it a dict instead of a list of a dict) you'll get the correct reply to address.
