### ISSUE TITLE
Get bulk email status doesn't work

### ISSUE THREAD

**Issue by Agathe-Brusset** [mailersend/mailersend-python#73]
A customer found a bug in our Python SDK:
Send in Bulk: https://github.com/mailersend/mailersend-python#send-bulk-email
Get bulk email status: https://github.com/mailersend/mailersend-python#get-bulk-email-status

```
from mailersend import emails
mailer = mailersend.NewEmail(api_key)
```

That doesn’t work because NewEmail is not a class from “mailersend” but from “emails”.
The correct should be:

```
from mailersend import emails
mailer = emails.NewEmail(api_key)
```

Reported by Cesar [here](https://themailergroup.slack.com/archives/C01G23Y28NL/p1663779421499759).

![Image](https://user-images.githubusercontent.com/73846155/191692945-c77a637b-769b-4ef4-aa2a-49e4dfee9bad.png)

**Comment by igorhrcek** [comment]
Issue resolved.
