### ISSUE TITLE
AttributeError: 'NewHelper' object has no attribute 'api_base'

### ISSUE THREAD

**Issue by hardiksondagar** [mailersend/mailersend-python#99]
**Describe the bug**
AttributeError: 'NewHelper' object has no attribute 'api_base'

**To Reproduce**
Initialize helper class and use it
```
helper = utils.NewHelper()
```

**Expected behavior**
It should have worked without error

**Comment by hardiksondagar** [comment]
Attempted to make a fix here - https://github.com/mailersend/mailersend-python/pull/100

**Comment by igorhrcek** [comment]
I cannot reproduce this issue.
